### ISSUE TITLE
jinja2.exceptions.TemplateNotFound

### ISSUE THREAD

**Issue by dgiglio** [Aparicio99/conkyrc#1]
Hi, I get this error when trying to run the script:

Traceback (most recent call last):
  File "/home/daniele/devel/proj/conkyrc/./conkyrc-generator.py", line 136, in <module>
    template = env.get_template('conkyrc-template')
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: conkyrc-template

My system:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by Aparicio99** [comment]
Hi @dgiglio,
The absolute template path was hard-coded, but this commit fixes that.
If executing from the repository directory, you can run the same command as before and it should work now.
